"use strict";
console.log("\n\n------------- Age calculator -----------------");
var C_Month = 11;
var C_year = 2023;
var C_day = 24;
console.log("Current date", C_day + "-" + C_Month + "-" + C_year);
var B_Month = 5;
var B_year = 1997;
var B_day = 12;
console.log("Birth date", B_day + "-" + B_Month + "-" + B_year);
var age = C_year - B_year;
console.log("Age = ", age);
console.log("\n\n------------- Area calculator -----------------");
var width = 10;
console.log("Width of a rectangle ", width);
var height = 5;
console.log("Height of a rectangle ", height);
var area = width * height;
console.log("area of a rectangle ", area);
console.log("\n\n------------- Area calculation- Circle -----------------");
var Radius = 20;
console.log("Radius of a circle ", Radius);
var area = 3.14 * (Radius * Radius);
console.log("area of a circle ", area);
console.log("\n\n------------- Area calculation- Cube -----------------");
var a = 5;
console.log("edge of a cube ", a);
var area = 6 * (a * a);
console.log("area of a cube ", area);
console.log("\n\n------------- Temprature from fahrenheit to celsius -----------------");
var fahrenheitTemp = 12;
console.log("Temprature in fahrenheit ", fahrenheitTemp);
var TempratureInCelsius = (32 * fahrenheitTemp - 32) * 5 / 9;
console.log("Temprature from fahrenheit to celsius", TempratureInCelsius.toFixed(2));
console.log("\n\n------------- Time into minutes and seconds -----------------");
var totaltime = 650;
console.log("total time in seconds", totaltime);
var timeinMin = ~~(totaltime / 60);
var timeinsec = totaltime % 60;
console.log("Time in minutes and seconds ", timeinMin, "", timeinsec);
console.log("\n\n------------- Days into week and days -----------------");
var totaldays = 20;
console.log("total days", totaldays);
var weeks = ~~(totaldays / 7);
var days = totaldays % 7;
console.log("Days into weeks and days ", weeks, "", days);
